#  Copyright (c) 2017 SHIELD, UBIWHERE
# ALL RIGHTS RESERVED.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Neither the name of the SHIELD, UBIWHERE nor the names of its
# contributors may be used to endorse or promote products derived from this
# software without specific prior written permission.
#
# This work has been performed in the framework of the SHIELD project,
# funded by the European Commission under Grant number 700199 through the
# Horizon 2020 program. The authors would like to acknowledge the contributions
# of their colleagues of the SHIELD partner consortium (www.shield-h2020.eu).



#
# Dashboard Quality Assurance environment
#

FROM centos:7

LABEL project="${CNTR_PROJECT}"

# Dependencies
RUN yum update -y && \
    yum install -y https://centos7.iuscommunity.org/ius-release.rpm \
    yum makecache fast && \
    yum install -y python36u python36u-pip && \
    pip3.6 install --upgrade pip && \
    curl --silent --location https://rpm.nodesource.com/setup_8.x | bash - && \
    yum update -y && \
    yum install -y nodejs && \
    npm i -g argv@0.0.2 cucumber-html-reporter@2.0.3 canned@0.3.10 && \
    yum clean all

ENV NODE_PATH /usr/lib/node_modules

WORKDIR ${FOLDER_TESTS_BASEPATH}

# Mock vNSF Orchestrator.
CMD ["canned", "${CNTR_FOLDER_VNSFO}", "-p", "${CNTR_MOCK_VNSFO_PORT}"]

ENTRYPOINT ["${CNTR_FOLDER_DEV}/docker/setup-qa.sh"]
