FROM python:2.7
MAINTAINER Tiago Teixeira "tteixeira@ubiwhere.com"

LABEL project="${CNTR_PROJECT}"

ENV VERSION=10.0.3

RUN set -x \
    && apt-get -y update \
    && apt-get install -y libffi-dev python-dev libssl-dev mysql-client python-mysqldb \
    && apt-get -y clean

#
# As of 26.04.2018 (probably since the 14.0.0.0b1 release), the python requirements
# for keystone render the version used here to stop working as it should.
# The reason for this is the requirements file not locking the versions on the
# libraries it imports. This leads to use the latest ones which causes keystone
# behave differently from when the release defined here works.
# Namely, keystoneauth1 which expected behaviour was for v3.4.0 but since the
# aforementioned update it operates as per v3.5.0 causing all sorts of problems
# when validating tokens, yielding an HTTP 400 Bad request response with
# the message "fetch_token() got an unexpected keyword argument 'allow_expired'"
#
# The workaround for this was to get hold of a version working as it should and
# produce a requirements file to lock down the library versions to use.
#

COPY requirements-keystone_lock.txt /root/.

RUN curl -fSL https://github.com/openstack/keystone/archive/${VERSION}.tar.gz -o keystone-${VERSION}.tar.gz \
    && tar xvf keystone-${VERSION}.tar.gz \
    && cd keystone-${VERSION} \
    && pip install pika==0.10.0 \
    && pip install -r /root/requirements-keystone_lock.txt \
    && PBR_VERSION=${VERSION}  pip install . \
    && pip install uwsgi MySQL-python \
    && cp -r etc /etc/keystone \
    && cd - \
    && rm -rf keystone-${VERSION}*

RUN apt install python-openstackclient -y

RUN apt install -y python3-pip
RUN pip3 install requests


COPY keystone.conf /etc/keystone/keystone.conf
COPY keystone.sql /root/keystone.sql
COPY keystone-setup-role.py /root/keystone-setup-role.py

# Add bootstrap script and make it executable
COPY setup-keystone.sh /etc/bootstrap.sh
RUN chown root:root /etc/bootstrap.sh && chmod a+x /etc/bootstrap.sh

ENTRYPOINT ["/etc/bootstrap.sh"]
